id = "jellybeans-zed"
name = "Jellybeans Zed"
description = "A colorful dark theme for Zed editor inspired by Jellybeans color scheme."
version = "0.0.1"
schema_version = 1
authors = ["Snehasish Dawn <snehasishdawn29@gmail.com>"]
repository = "https://github.com/sdawn29/jellybeans-zed"
